// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjHb_D-axROEVHnc7zzGbYJf8zCjyG_-E',
    appId: '1:486446307419:web:022737b3e95929d421c77e',
    messagingSenderId: '486446307419',
    projectId: 'sports-access-app',
    authDomain: 'sports-access-app.firebaseapp.com',
    storageBucket: 'sports-access-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxCnDzfLCM7ydgT_JKuFpJyHXz7hy5OAU',
    appId: '1:486446307419:android:410815439f51d7d821c77e',
    messagingSenderId: '486446307419',
    projectId: 'sports-access-app',
    storageBucket: 'sports-access-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeiaxo6NCzr0pDH3r4nDWwSngWqKt7TMw',
    appId: '1:486446307419:ios:92d2fd0dd3122ddc21c77e',
    messagingSenderId: '486446307419',
    projectId: 'sports-access-app',
    storageBucket: 'sports-access-app.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeiaxo6NCzr0pDH3r4nDWwSngWqKt7TMw',
    appId: '1:486446307419:ios:92d2fd0dd3122ddc21c77e',
    messagingSenderId: '486446307419',
    projectId: 'sports-access-app',
    storageBucket: 'sports-access-app.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjHb_D-axROEVHnc7zzGbYJf8zCjyG_-E',
    appId: '1:486446307419:web:59a31abbc92b5dda21c77e',
    messagingSenderId: '486446307419',
    projectId: 'sports-access-app',
    authDomain: 'sports-access-app.firebaseapp.com',
    storageBucket: 'sports-access-app.firebasestorage.app',
  );
}
